import sys
import struct
import os

if len(sys.argv) < 3:
    print("Usage: python convert_bmp_to_oft.py <input_font.bmp> <output_font.bin>")
    print("This script extracts luminance from a 32-bit BMP generated by font2oft")
    print("and thresholds it to 1-bit, discarding any Windows ClearType artifacts.")
    sys.exit(1)

input_bmp = sys.argv[1]
output_bin = sys.argv[2]

if not os.path.exists(input_bmp):
    print(f"Error: {input_bmp} not found.")
    sys.exit(1)

with open(input_bmp, 'rb') as f:
    bmp_data = f.read()

# Parse BMP Header
offset = struct.unpack_from('<I', bmp_data, 10)[0]
width = struct.unpack_from('<i', bmp_data, 18)[0]
height = struct.unpack_from('<i', bmp_data, 22)[0]
bpp = struct.unpack_from('<H', bmp_data, 28)[0]

print(f"Reading BMP: width={width}, height={height}, bpp={bpp}, offset={offset}")

if bpp not in (24, 32):
    print(f"Warning: Expected a 24-bit or 32-bit BMP, but got {bpp}-bit. The script may fail or produce unexpected results.")

# Ensure we have a bottom-up parsing strategy for positive height BMPs
is_bottom_up = height > 0
height = abs(height)

pixels = []
row_bytes = ((width * bpp + 31) // 32) * 4
bytes_per_pixel = bpp // 8

for y in range(height):
    if is_bottom_up:
        row_offset = offset + (height - 1 - y) * row_bytes
    else:
        row_offset = offset + y * row_bytes
        
    row = bmp_data[row_offset:row_offset+row_bytes]
    row_pixels = []
    
    for x in range(width):
        idx = x * bytes_per_pixel
        if idx + 2 < len(row):
            b = row[idx]
            g = row[idx+1]
            r = row[idx+2]
            
            # Simple luminance calculation
            lum = 0.299*r + 0.587*g + 0.114*b
            
            # Thresholding (dark pixels are font, light are background)
            if lum < 128:
                row_pixels.append(1)
            else:
                row_pixels.append(0)
        else:
            row_pixels.append(0)
            
    pixels.append(row_pixels)

# Determine the number of characters based on height (assuming 8px width)
# Font2oft usually outputs 256 characters stacked vertically
char_count = 256
char_height = height // char_count

print(f"Detected character count: {char_count}, Character height: {char_height}")

def make_bin():
    # OSLFont v01 Header (64 bytes)
    header = bytearray(64)
    header[0:12] = b'OSLFont v01\0'
    header[12:16] = bytes([1, 1, 0, 0]) # bitplanes=1, variable=1
    header[16:20] = struct.pack('<I', width)
    header[20:24] = struct.pack('<I', char_height)
    header[24:28] = struct.pack('<I', 1)

    # 256 bytes width table (assuming monospace for now)
    width_table = bytearray([width]*256)

    pixel_data = bytearray()
    for char_idx in range(char_count):
        for row_idx in range(char_height):
            # Check if row exists (in case height isn't perfectly divisible by 256)
            pixel_row_idx = char_idx * char_height + row_idx
            if pixel_row_idx < len(pixels):
                row = pixels[pixel_row_idx]
            else:
                row = [0] * width
                
            byte_val = 0
            for x in range(width):
                if x < len(row) and row[x] == 1:
                    byte_val |= (1 << x) # leftmost pixel is bit 0 for OSLFont
            pixel_data.append(byte_val)
            
    return header + width_table + pixel_data

with open(output_bin, 'wb') as f:
    f.write(make_bin())

print(f"Success: Wrote valid OSLFont data to {output_bin}")
